networks:
  sigue-adelante-radio:
    external: true

services:
  autentication-backend:
    container_name: sar-post-backend
    image: sar-post-backend:1.0.0
    build: .
    restart: always
    networks:
      - sigue-adelante-radio
    environment:
      PORT: 80
      # PRODUCTION: true
      DATABASE_URL: $DATABASE_URL
      VAULT_HOST: $VAULT_HOST
      VAULT_PORT: $VAULT_PORT
      ROLE_ID: $ROLE_ID
      SECRET_ID: $SECRET_ID
    
